# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Clayton Cohn
  admin_email: ccohn@marketaction.com
  admin_password: slgels
  email_provider_username: <%= ENV["claytoncohn"] %>
  email_provider_password: <%= ENV["SLG73els!"] %>
  domain_name: localhost:3000
  secret_key_base: 0cdb9f3dd6828eb8ffc7ddca7d9a7a39b65e8af1ca3713e3664eb5499038eb1ff4f4d016c4ff35781a25067535ac1ccecc34f08fae2445316fbac31b2a11de5b

test:
  domain_name: localhost:3000 
  secret_key_base: ed5d3458d9170901e49be72a438c6581cb0c5fba8982bc2266cfce47dd0d9c4e985805fb1f27a31d986804e31857bffb0f207f9ae318ad9cbe80ff687eb8765b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["Clayton Cohn"] %>
  admin_email: <%= ENV["ccohn@marketaction.com"] %>
  admin_password: <%= ENV["slgels"] %>
  email_provider_username: <%= ENV["claytoncohn"] %>
  email_provider_password: <%= ENV["SLG73els!"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
